# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi-Admin

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

# Spring配置
spring:
  profiles:
    active: dev
  config:
    import: classpath:framework-defaults.yml
