<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.ruoyi</groupId>
        <artifactId>ruoyi</artifactId>
        <version>3.9.2</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <artifactId>system-sdk-http</artifactId>

    <name>system-sdk-http</name>
    <url>http://www.ruoyi.vip</url>
    <description>系统 SDK - HTTP 模块</description>

    <dependencies>
        <!-- SDK 核心依赖 -->
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>system-sdk-core</artifactId>
        </dependency>

        <!-- JSON 处理 -->
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>
    </dependencies>

</project>
